import { auth, db } from "./firebase.js";
import { collection, addDoc, getDocs, doc, updateDoc, deleteDoc, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js";
import { onAuthStateChanged, signOut } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js";

const form=document.getElementById("burialForm"), userEmail=document.getElementById("userEmail"), list=document.getElementById("burialList"), search=document.getElementById("burialSearch");
const saveBtn=document.getElementById("saveBurialBtn"), updateBtn=document.getElementById("updateBurialBtn"), cancelBtn=document.getElementById("cancelEditBtn"), resetBtn=document.getElementById("resetButton"), message=document.getElementById("formMessage"), formTitle=document.getElementById("formTitle");
let currentUser=null, editingId=null, allRecords=[];

onAuthStateChanged(auth, async user=>{ if(!user){location.href="../index.html";return;} currentUser=user; userEmail.textContent=user.email||"User"; await loadRecords(); });
document.getElementById("logoutButton")?.addEventListener("click",async()=>{await signOut(auth);location.href="../index.html";});
function esc(v=""){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));}
function val(id){return document.getElementById(id)?.value.trim()||"";}
function dataFromForm(){return {refNo:val("refNo"),name:val("name"),relationship:val("relationship"),age:val("age"),occupation:val("occupation"),locality:val("locality"),causeOfDeath:val("causeOfDeath"),dateOfDeath:document.getElementById("dateOfDeath").value,dateOfBurial:document.getElementById("dateOfBurial").value,placeOfBurial:val("placeOfBurial"),minister:val("minister"),createdBy:currentUser.uid,createdByEmail:currentUser.email||""};}
const textFields=["refNo","name","relationship","age","occupation","locality","causeOfDeath","placeOfBurial","minister"], dateFields=["dateOfDeath","dateOfBurial"];
function resetForm(){editingId=null;form.reset();formTitle.textContent="New Burial Record";saveBtn.hidden=false;updateBtn.hidden=true;cancelBtn.hidden=true;message.textContent="";message.className="burial-message";}
function populate(data,id){editingId=id;textFields.forEach(k=>document.getElementById(k).value=data[k]||"");dateFields.forEach(k=>document.getElementById(k).value=data[k]||"");formTitle.textContent="Edit Burial Record";saveBtn.hidden=true;updateBtn.hidden=false;cancelBtn.hidden=false;window.scrollTo({top:0,behavior:"smooth"});}
cancelBtn.addEventListener("click",resetForm); resetBtn.addEventListener("click",()=>setTimeout(resetForm,0));
form.addEventListener("submit",async e=>{e.preventDefault();if(!currentUser)return;const data=dataFromForm();if(!data.refNo||!data.name||!data.dateOfDeath||!data.dateOfBurial){message.textContent="Please enter Ref. No., Name, Date of Death and Date of Burial.";message.className="burial-message error";return;}try{saveBtn.disabled=true;updateBtn.disabled=true;if(editingId){await updateDoc(doc(db,"burials",editingId),{...data,updatedBy:currentUser.uid,updatedByEmail:currentUser.email||"",updatedAt:serverTimestamp()});message.textContent="Burial record updated successfully.";}else{await addDoc(collection(db,"burials"),{...data,createdAt:serverTimestamp()});message.textContent="Burial record saved successfully.";}message.className="burial-message success";await loadRecords();const ok=message.textContent;resetForm();message.textContent=ok;message.className="burial-message success";}catch(error){console.error(error);message.textContent=error.code==="permission-denied"?"Firestore permission denied. Please add the Burials collection to your Security Rules.":"Could not save the Burial record: "+error.message;message.className="burial-message error";}finally{saveBtn.disabled=false;updateBtn.disabled=false;}});
updateBtn.addEventListener("click",()=>form.requestSubmit());
async function deleteRecord(id,label){if(!confirm(`Delete the Burial record for "${label}"?\n\nThis action cannot be undone.`))return;try{await deleteDoc(doc(db,"burials",id));await loadRecords();}catch(e){alert("Could not delete the Burial record: "+e.message);}}
function fmt(v){if(!v)return "";const m=String(v).match(/^(\d{4})-(\d{2})-(\d{2})$/);return m?`${m[3]}-${m[2]}-${m[1]}`:String(v);}
function renderRecords(records){if(!records.length){list.innerHTML='<tr><td colspan="8" class="register-empty">No burial records found.</td></tr>';return;}list.innerHTML=records.map(({id,data})=>`<tr><td class="ref-cell">${esc(data.refNo)}</td><td class="name-cell">${esc(data.name)}</td><td>${esc(data.relationship)}</td><td>${esc(data.age)}</td><td>${esc(fmt(data.dateOfDeath))}</td><td>${esc(fmt(data.dateOfBurial))}</td><td>${esc(data.placeOfBurial)}</td><td><div class="table-actions"><button type="button" class="table-btn edit-record" data-id="${esc(id)}">Edit</button><button type="button" class="table-btn delete-record" data-id="${esc(id)}">Delete</button></div></td></tr>`).join("");list.querySelectorAll(".edit-record").forEach(b=>b.addEventListener("click",()=>{const r=allRecords.find(x=>x.id===b.dataset.id);if(r)populate(r.data,r.id);}));list.querySelectorAll(".delete-record").forEach(b=>b.addEventListener("click",()=>{const r=allRecords.find(x=>x.id===b.dataset.id);if(r)deleteRecord(r.id,r.data.name||"");}));}
async function loadRecords(){if(!currentUser)return;list.innerHTML='<tr><td colspan="8" class="register-empty">Loading burial records...</td></tr>';try{const snap=await getDocs(collection(db,"burials"));allRecords=snap.docs.map(d=>({id:d.id,data:d.data()})).sort((a,b)=>(b.data.createdAt?.seconds||0)-(a.data.createdAt?.seconds||0));renderRecords(allRecords);}catch(e){console.error(e);list.innerHTML='<tr><td colspan="8" class="register-empty">Could not load burial records. Check Firestore rules.</td></tr>';}}
search.addEventListener("input",()=>{const term=search.value.trim().toLowerCase();renderRecords(allRecords.filter(({data})=>[data.refNo,data.name,data.relationship,data.occupation,data.locality,data.causeOfDeath,data.placeOfBurial,data.minister].some(v=>String(v||"").toLowerCase().includes(term))));});
