import { auth, db } from "./firebase.js";
import { onAuthStateChanged, signOut } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js";
import { collection, addDoc, getDocs, doc, updateDoc, deleteDoc, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js";
const $=id=>document.getElementById(id); const form=$("subscriptionForm"); let editingId=null, allCollections=[], familyCards=[];
const money=n=>`₹${Number(n||0).toLocaleString("en-IN",{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const localDate=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`};
const localMonth=()=>localDate().slice(0,7);
function formatDate(s){if(!s)return"—";const m=String(s).match(/^(\d{4})-(\d{2})-(\d{2})$/);if(m)return`${m[3]}/${m[2]}/${m[1]}`;const d=String(s).match(/^(\d{2})[/-](\d{2})[/-](\d{4})$/);return d?`${d[1]}/${d[2]}/${d[3]}`:String(s)}
function monthLabel(m){if(!m)return"";const[y,x]=m.split("-");return new Date(+y,+x-1,1).toLocaleDateString("en-IN",{month:"long",year:"numeric"})}
function setMessage(t,type){$("subscriptionMessage").textContent=t;$("subscriptionMessage").className=`subscription-message ${type}`;setTimeout(()=>{$("subscriptionMessage").textContent="";$ ("subscriptionMessage").className="subscription-message"},3500)}
function populateFamilyCards(){const select=$("familyCardNo");select.innerHTML='<option value="">Select Family Card</option>'+familyCards.map(x=>`<option value="${esc(x.familyCardNo)}">${esc(x.familyCardNo)} — ${esc(x.name||"")}</option>`).join("")}
function syncFamilyName(){const card=familyCards.find(x=>x.familyCardNo===$("familyCardNo").value);$("familyName").value=card?.name||""}
async function loadFamilyCards(){const snap=await getDocs(collection(db,"familyCards"));familyCards=snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>String(a.familyCardNo||"").localeCompare(String(b.familyCardNo||"")));populateFamilyCards()}
async function loadCollections(){try{const snap=await getDocs(collection(db,"familySubscriptions"));allCollections=snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(b.collectionDate||"").localeCompare(a.collectionDate||""));render()}catch(e){console.error(e);$("subscriptionList").innerHTML=`<tr><td colspan="8" class="register-empty">${e?.code==="permission-denied"?"Firebase permission denied. Add the familySubscriptions rule from firestore-family-subscriptions-rules.txt.":"Could not load subscription collections."}</td></tr>`}}
function render(){const m=$("subscriptionMonthFilter").value;const rows=allCollections.filter(x=>(x.month||(x.collectionDate||"").slice(0,7))===m);const total=rows.reduce((s,x)=>s+Number(x.amount||0),0);$("subscriptionTotalEntries").textContent=rows.length;$("subscriptionMonthlyTotal").textContent=money(total);$("subscriptionPrintLink").href=`subscription-print.html?month=${encodeURIComponent(m)}`;$("subscriptionList").innerHTML=rows.length?rows.map(x=>`<tr><td>${esc(formatDate(x.collectionDate))}</td><td>${esc(x.familyCardNo)}</td><td>${esc(x.familyName)}</td><td>${esc(x.receiptNo||"—")}</td><td>${esc(x.paymentMode||"—")}</td><td class="amount-col">${money(x.amount)}</td><td>${esc(x.remarks||"—")}</td><td><div class="table-actions"><button class="table-edit" data-edit="${x.id}">Edit</button><button class="table-delete" data-delete="${x.id}">Delete</button></div></td></tr>`).join(""):`<tr><td colspan="8" class="register-empty">No collections recorded for ${esc(monthLabel(m))}.</td></tr>`;document.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>editCollection(b.dataset.edit));document.querySelectorAll("[data-delete]").forEach(b=>b.onclick=()=>removeCollection(b.dataset.delete))}
function resetForm(){form.reset();$("collectionDate").value=localDate();$("collectionMonth").value=localMonth();$("subscriptionPaymentMode").value="Cash";$("familyName").value="";editingId=null;$("subscriptionFormTitle").textContent="New Subscription Entry";$("saveSubscriptionBtn").textContent="Save Collection";$("cancelSubscriptionEditBtn").hidden=true}
function editCollection(id){const x=allCollections.find(a=>a.id===id);if(!x)return;$("collectionDate").value=x.collectionDate||"";$("collectionMonth").value=x.month||(x.collectionDate||"").slice(0,7);$("familyCardNo").value=x.familyCardNo||"";$("familyName").value=x.familyName||"";$("subscriptionAmount").value=x.amount??"";$("receiptNo").value=x.receiptNo||"";$("subscriptionPaymentMode").value=x.paymentMode||"Cash";$("subscriptionRemarks").value=x.remarks||"";editingId=id;$("subscriptionFormTitle").textContent="Edit Subscription Entry";$("saveSubscriptionBtn").textContent="Update Collection";$("cancelSubscriptionEditBtn").hidden=false;window.scrollTo({top:0,behavior:"smooth"})}
async function removeCollection(id){const x=allCollections.find(a=>a.id===id);if(!x||!confirm(`Delete collection ${money(x.amount)} for ${x.familyName||x.familyCardNo}?`))return;try{await deleteDoc(doc(db,"familySubscriptions",id));await loadCollections();setMessage("Collection deleted.","success")}catch(e){console.error(e);setMessage("Could not delete the collection: "+(e?.message||"Please try again."),"error")}}
form.addEventListener("submit",async e=>{e.preventDefault();const card=familyCards.find(x=>x.familyCardNo===$("familyCardNo").value);const data={collectionDate:$("collectionDate").value,month:$("collectionMonth").value,familyCardNo:$("familyCardNo").value,familyName:card?.name||$("familyName").value.trim(),amount:Number($("subscriptionAmount").value||0),receiptNo:$("receiptNo").value.trim(),paymentMode:$("subscriptionPaymentMode").value,remarks:$("subscriptionRemarks").value.trim()};if(!data.familyCardNo||!data.familyName)return setMessage("Please select a Family Card.","error");if(!(data.amount>=0))return setMessage("Please enter a valid amount.","error");$("saveSubscriptionBtn").disabled=true;try{if(editingId)await updateDoc(doc(db,"familySubscriptions",editingId),data);else await addDoc(collection(db,"familySubscriptions"),{...data,createdAt:serverTimestamp()});setMessage(editingId?"Collection updated successfully.":"Collection saved successfully.","success");resetForm();await loadCollections()}catch(e){console.error(e);setMessage(e?.code==="permission-denied"?"Firebase permission denied. Add the familySubscriptions rule from firestore-family-subscriptions-rules.txt.":`Could not save the collection: ${e?.message||"Please try again."}`,"error")}finally{$("saveSubscriptionBtn").disabled=false}});
$("familyCardNo").addEventListener("change",syncFamilyName);$("subscriptionMonthFilter").addEventListener("change",render);$("collectionDate").addEventListener("change",()=>{if($("collectionDate").value)$("collectionMonth").value=$("collectionDate").value.slice(0,7)});$("cancelSubscriptionEditBtn").onclick=resetForm;$("clearSubscriptionBtn").onclick=()=>setTimeout(resetForm,0);$("logoutButton").onclick=async()=>{await signOut(auth);window.location.href="../index.html"};
$("subscriptionMonthFilter").value=localMonth();resetForm();onAuthStateChanged(auth,async user=>{if(!user){window.location.href="../index.html";return}$("userEmail").textContent=user.email||"User";try{await loadFamilyCards();await loadCollections()}catch(e){console.error(e)}});
